sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRfzYJLhWDgp4LLpY11
    access-key-secret: fIBeCebaCp2HxUYhzLU1PRkpiyX4ki
    bucket-name: sky-take-out-lanxi
